/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRiderDashboardRouteImport } from './routes/_app/rider-dashboard'
import { Route as AppRestaurantDashboardRouteImport } from './routes/_app/restaurant-dashboard'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppMyRestaurantRouteImport } from './routes/_app/my-restaurant'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppCartRouteImport } from './routes/_app/cart'
import { Route as AppAddressesRouteImport } from './routes/_app/addresses'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin.index'
import { Route as AppRestaurantsRestaurantIdRouteImport } from './routes/_app/restaurants.$restaurantId'
import { Route as AppRestaurantReviewsRouteImport } from './routes/_app/restaurant.reviews'
import { Route as AppRestaurantPromotionsRouteImport } from './routes/_app/restaurant.promotions'
import { Route as AppRestaurantOrdersRouteImport } from './routes/_app/restaurant.orders'
import { Route as AppRestaurantNotificationSettingsRouteImport } from './routes/_app/restaurant.notification-settings'
import { Route as AppRestaurantMenuRouteImport } from './routes/_app/restaurant.menu'
import { Route as AppRestaurantAnalyticsRouteImport } from './routes/_app/restaurant.analytics'
import { Route as AppMyRestaurantSettingsRouteImport } from './routes/_app/my-restaurant_.settings'
import { Route as AppAdminRiderRouteImport } from './routes/_app/admin.rider'
import { Route as AppAdminEatRouteImport } from './routes/_app/admin.eat'
import { Route as AppAdminAppVersionRouteImport } from './routes/_app/admin.app-version'
import { Route as AppAdminOrdersIndexRouteImport } from './routes/_app/admin.orders.index'
import { Route as AppAdminUsersUserIdRouteImport } from './routes/_app/admin.users.$userId'
import { Route as AppAdminRestaurantsRestaurantIdRouteImport } from './routes/_app/admin.restaurants.$restaurantId'
import { Route as AppAdminOrdersOrderIdRouteImport } from './routes/_app/admin.orders.$orderId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRiderDashboardRoute = AppRiderDashboardRouteImport.update({
  id: '/rider-dashboard',
  path: '/rider-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantDashboardRoute = AppRestaurantDashboardRouteImport.update({
  id: '/restaurant-dashboard',
  path: '/restaurant-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMyRestaurantRoute = AppMyRestaurantRouteImport.update({
  id: '/my-restaurant',
  path: '/my-restaurant',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppAddressesRoute = AppAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantsRestaurantIdRoute =
  AppRestaurantsRestaurantIdRouteImport.update({
    id: '/restaurants/$restaurantId',
    path: '/restaurants/$restaurantId',
    getParentRoute: () => AppRoute,
  } as any)
const AppRestaurantReviewsRoute = AppRestaurantReviewsRouteImport.update({
  id: '/restaurant/reviews',
  path: '/restaurant/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantPromotionsRoute = AppRestaurantPromotionsRouteImport.update({
  id: '/restaurant/promotions',
  path: '/restaurant/promotions',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantOrdersRoute = AppRestaurantOrdersRouteImport.update({
  id: '/restaurant/orders',
  path: '/restaurant/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantNotificationSettingsRoute =
  AppRestaurantNotificationSettingsRouteImport.update({
    id: '/restaurant/notification-settings',
    path: '/restaurant/notification-settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppRestaurantMenuRoute = AppRestaurantMenuRouteImport.update({
  id: '/restaurant/menu',
  path: '/restaurant/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantAnalyticsRoute = AppRestaurantAnalyticsRouteImport.update({
  id: '/restaurant/analytics',
  path: '/restaurant/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppMyRestaurantSettingsRoute = AppMyRestaurantSettingsRouteImport.update({
  id: '/my-restaurant_/settings',
  path: '/my-restaurant/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRiderRoute = AppAdminRiderRouteImport.update({
  id: '/admin/rider',
  path: '/admin/rider',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEatRoute = AppAdminEatRouteImport.update({
  id: '/admin/eat',
  path: '/admin/eat',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAppVersionRoute = AppAdminAppVersionRouteImport.update({
  id: '/admin/app-version',
  path: '/admin/app-version',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOrdersIndexRoute = AppAdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersUserIdRoute = AppAdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRestaurantsRestaurantIdRoute =
  AppAdminRestaurantsRestaurantIdRouteImport.update({
    id: '/admin/restaurants/$restaurantId',
    path: '/admin/restaurants/$restaurantId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminOrdersOrderIdRoute = AppAdminOrdersOrderIdRouteImport.update({
  id: '/admin/orders/$orderId',
  path: '/admin/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/addresses': typeof AppAddressesRoute
  '/cart': typeof AppCartRoute
  '/home': typeof AppHomeRoute
  '/my-restaurant': typeof AppMyRestaurantRoute
  '/orders': typeof AppOrdersRoute
  '/profile': typeof AppProfileRoute
  '/restaurant-dashboard': typeof AppRestaurantDashboardRoute
  '/rider-dashboard': typeof AppRiderDashboardRoute
  '/admin/app-version': typeof AppAdminAppVersionRoute
  '/admin/eat': typeof AppAdminEatRoute
  '/admin/rider': typeof AppAdminRiderRoute
  '/my-restaurant/settings': typeof AppMyRestaurantSettingsRoute
  '/restaurant/analytics': typeof AppRestaurantAnalyticsRoute
  '/restaurant/menu': typeof AppRestaurantMenuRoute
  '/restaurant/notification-settings': typeof AppRestaurantNotificationSettingsRoute
  '/restaurant/orders': typeof AppRestaurantOrdersRoute
  '/restaurant/promotions': typeof AppRestaurantPromotionsRoute
  '/restaurant/reviews': typeof AppRestaurantReviewsRoute
  '/restaurants/$restaurantId': typeof AppRestaurantsRestaurantIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/admin/orders/$orderId': typeof AppAdminOrdersOrderIdRoute
  '/admin/restaurants/$restaurantId': typeof AppAdminRestaurantsRestaurantIdRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/admin/orders/': typeof AppAdminOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/addresses': typeof AppAddressesRoute
  '/cart': typeof AppCartRoute
  '/home': typeof AppHomeRoute
  '/my-restaurant': typeof AppMyRestaurantRoute
  '/orders': typeof AppOrdersRoute
  '/profile': typeof AppProfileRoute
  '/restaurant-dashboard': typeof AppRestaurantDashboardRoute
  '/rider-dashboard': typeof AppRiderDashboardRoute
  '/admin/app-version': typeof AppAdminAppVersionRoute
  '/admin/eat': typeof AppAdminEatRoute
  '/admin/rider': typeof AppAdminRiderRoute
  '/my-restaurant/settings': typeof AppMyRestaurantSettingsRoute
  '/restaurant/analytics': typeof AppRestaurantAnalyticsRoute
  '/restaurant/menu': typeof AppRestaurantMenuRoute
  '/restaurant/notification-settings': typeof AppRestaurantNotificationSettingsRoute
  '/restaurant/orders': typeof AppRestaurantOrdersRoute
  '/restaurant/promotions': typeof AppRestaurantPromotionsRoute
  '/restaurant/reviews': typeof AppRestaurantReviewsRoute
  '/restaurants/$restaurantId': typeof AppRestaurantsRestaurantIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/admin/orders/$orderId': typeof AppAdminOrdersOrderIdRoute
  '/admin/restaurants/$restaurantId': typeof AppAdminRestaurantsRestaurantIdRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/admin/orders': typeof AppAdminOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/addresses': typeof AppAddressesRoute
  '/_app/cart': typeof AppCartRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/my-restaurant': typeof AppMyRestaurantRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/restaurant-dashboard': typeof AppRestaurantDashboardRoute
  '/_app/rider-dashboard': typeof AppRiderDashboardRoute
  '/_app/admin/app-version': typeof AppAdminAppVersionRoute
  '/_app/admin/eat': typeof AppAdminEatRoute
  '/_app/admin/rider': typeof AppAdminRiderRoute
  '/_app/my-restaurant_/settings': typeof AppMyRestaurantSettingsRoute
  '/_app/restaurant/analytics': typeof AppRestaurantAnalyticsRoute
  '/_app/restaurant/menu': typeof AppRestaurantMenuRoute
  '/_app/restaurant/notification-settings': typeof AppRestaurantNotificationSettingsRoute
  '/_app/restaurant/orders': typeof AppRestaurantOrdersRoute
  '/_app/restaurant/promotions': typeof AppRestaurantPromotionsRoute
  '/_app/restaurant/reviews': typeof AppRestaurantReviewsRoute
  '/_app/restaurants/$restaurantId': typeof AppRestaurantsRestaurantIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/admin/orders/$orderId': typeof AppAdminOrdersOrderIdRoute
  '/_app/admin/restaurants/$restaurantId': typeof AppAdminRestaurantsRestaurantIdRoute
  '/_app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/_app/admin/orders/': typeof AppAdminOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/addresses'
    | '/cart'
    | '/home'
    | '/my-restaurant'
    | '/orders'
    | '/profile'
    | '/restaurant-dashboard'
    | '/rider-dashboard'
    | '/admin/app-version'
    | '/admin/eat'
    | '/admin/rider'
    | '/my-restaurant/settings'
    | '/restaurant/analytics'
    | '/restaurant/menu'
    | '/restaurant/notification-settings'
    | '/restaurant/orders'
    | '/restaurant/promotions'
    | '/restaurant/reviews'
    | '/restaurants/$restaurantId'
    | '/admin/'
    | '/admin/orders/$orderId'
    | '/admin/restaurants/$restaurantId'
    | '/admin/users/$userId'
    | '/admin/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/addresses'
    | '/cart'
    | '/home'
    | '/my-restaurant'
    | '/orders'
    | '/profile'
    | '/restaurant-dashboard'
    | '/rider-dashboard'
    | '/admin/app-version'
    | '/admin/eat'
    | '/admin/rider'
    | '/my-restaurant/settings'
    | '/restaurant/analytics'
    | '/restaurant/menu'
    | '/restaurant/notification-settings'
    | '/restaurant/orders'
    | '/restaurant/promotions'
    | '/restaurant/reviews'
    | '/restaurants/$restaurantId'
    | '/admin'
    | '/admin/orders/$orderId'
    | '/admin/restaurants/$restaurantId'
    | '/admin/users/$userId'
    | '/admin/orders'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/addresses'
    | '/_app/cart'
    | '/_app/home'
    | '/_app/my-restaurant'
    | '/_app/orders'
    | '/_app/profile'
    | '/_app/restaurant-dashboard'
    | '/_app/rider-dashboard'
    | '/_app/admin/app-version'
    | '/_app/admin/eat'
    | '/_app/admin/rider'
    | '/_app/my-restaurant_/settings'
    | '/_app/restaurant/analytics'
    | '/_app/restaurant/menu'
    | '/_app/restaurant/notification-settings'
    | '/_app/restaurant/orders'
    | '/_app/restaurant/promotions'
    | '/_app/restaurant/reviews'
    | '/_app/restaurants/$restaurantId'
    | '/_app/admin/'
    | '/_app/admin/orders/$orderId'
    | '/_app/admin/restaurants/$restaurantId'
    | '/_app/admin/users/$userId'
    | '/_app/admin/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rider-dashboard': {
      id: '/_app/rider-dashboard'
      path: '/rider-dashboard'
      fullPath: '/rider-dashboard'
      preLoaderRoute: typeof AppRiderDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant-dashboard': {
      id: '/_app/restaurant-dashboard'
      path: '/restaurant-dashboard'
      fullPath: '/restaurant-dashboard'
      preLoaderRoute: typeof AppRestaurantDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-restaurant': {
      id: '/_app/my-restaurant'
      path: '/my-restaurant'
      fullPath: '/my-restaurant'
      preLoaderRoute: typeof AppMyRestaurantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/addresses': {
      id: '/_app/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AppAddressesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurants/$restaurantId': {
      id: '/_app/restaurants/$restaurantId'
      path: '/restaurants/$restaurantId'
      fullPath: '/restaurants/$restaurantId'
      preLoaderRoute: typeof AppRestaurantsRestaurantIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/reviews': {
      id: '/_app/restaurant/reviews'
      path: '/restaurant/reviews'
      fullPath: '/restaurant/reviews'
      preLoaderRoute: typeof AppRestaurantReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/promotions': {
      id: '/_app/restaurant/promotions'
      path: '/restaurant/promotions'
      fullPath: '/restaurant/promotions'
      preLoaderRoute: typeof AppRestaurantPromotionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/orders': {
      id: '/_app/restaurant/orders'
      path: '/restaurant/orders'
      fullPath: '/restaurant/orders'
      preLoaderRoute: typeof AppRestaurantOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/notification-settings': {
      id: '/_app/restaurant/notification-settings'
      path: '/restaurant/notification-settings'
      fullPath: '/restaurant/notification-settings'
      preLoaderRoute: typeof AppRestaurantNotificationSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/menu': {
      id: '/_app/restaurant/menu'
      path: '/restaurant/menu'
      fullPath: '/restaurant/menu'
      preLoaderRoute: typeof AppRestaurantMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/analytics': {
      id: '/_app/restaurant/analytics'
      path: '/restaurant/analytics'
      fullPath: '/restaurant/analytics'
      preLoaderRoute: typeof AppRestaurantAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-restaurant_/settings': {
      id: '/_app/my-restaurant_/settings'
      path: '/my-restaurant/settings'
      fullPath: '/my-restaurant/settings'
      preLoaderRoute: typeof AppMyRestaurantSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/rider': {
      id: '/_app/admin/rider'
      path: '/admin/rider'
      fullPath: '/admin/rider'
      preLoaderRoute: typeof AppAdminRiderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/eat': {
      id: '/_app/admin/eat'
      path: '/admin/eat'
      fullPath: '/admin/eat'
      preLoaderRoute: typeof AppAdminEatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/app-version': {
      id: '/_app/admin/app-version'
      path: '/admin/app-version'
      fullPath: '/admin/app-version'
      preLoaderRoute: typeof AppAdminAppVersionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/orders/': {
      id: '/_app/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AppAdminOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users/$userId': {
      id: '/_app/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/restaurants/$restaurantId': {
      id: '/_app/admin/restaurants/$restaurantId'
      path: '/admin/restaurants/$restaurantId'
      fullPath: '/admin/restaurants/$restaurantId'
      preLoaderRoute: typeof AppAdminRestaurantsRestaurantIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/orders/$orderId': {
      id: '/_app/admin/orders/$orderId'
      path: '/admin/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AppAdminOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAddressesRoute: typeof AppAddressesRoute
  AppCartRoute: typeof AppCartRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMyRestaurantRoute: typeof AppMyRestaurantRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRestaurantDashboardRoute: typeof AppRestaurantDashboardRoute
  AppRiderDashboardRoute: typeof AppRiderDashboardRoute
  AppAdminAppVersionRoute: typeof AppAdminAppVersionRoute
  AppAdminEatRoute: typeof AppAdminEatRoute
  AppAdminRiderRoute: typeof AppAdminRiderRoute
  AppMyRestaurantSettingsRoute: typeof AppMyRestaurantSettingsRoute
  AppRestaurantAnalyticsRoute: typeof AppRestaurantAnalyticsRoute
  AppRestaurantMenuRoute: typeof AppRestaurantMenuRoute
  AppRestaurantNotificationSettingsRoute: typeof AppRestaurantNotificationSettingsRoute
  AppRestaurantOrdersRoute: typeof AppRestaurantOrdersRoute
  AppRestaurantPromotionsRoute: typeof AppRestaurantPromotionsRoute
  AppRestaurantReviewsRoute: typeof AppRestaurantReviewsRoute
  AppRestaurantsRestaurantIdRoute: typeof AppRestaurantsRestaurantIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminOrdersOrderIdRoute: typeof AppAdminOrdersOrderIdRoute
  AppAdminRestaurantsRestaurantIdRoute: typeof AppAdminRestaurantsRestaurantIdRoute
  AppAdminUsersUserIdRoute: typeof AppAdminUsersUserIdRoute
  AppAdminOrdersIndexRoute: typeof AppAdminOrdersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddressesRoute: AppAddressesRoute,
  AppCartRoute: AppCartRoute,
  AppHomeRoute: AppHomeRoute,
  AppMyRestaurantRoute: AppMyRestaurantRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProfileRoute: AppProfileRoute,
  AppRestaurantDashboardRoute: AppRestaurantDashboardRoute,
  AppRiderDashboardRoute: AppRiderDashboardRoute,
  AppAdminAppVersionRoute: AppAdminAppVersionRoute,
  AppAdminEatRoute: AppAdminEatRoute,
  AppAdminRiderRoute: AppAdminRiderRoute,
  AppMyRestaurantSettingsRoute: AppMyRestaurantSettingsRoute,
  AppRestaurantAnalyticsRoute: AppRestaurantAnalyticsRoute,
  AppRestaurantMenuRoute: AppRestaurantMenuRoute,
  AppRestaurantNotificationSettingsRoute:
    AppRestaurantNotificationSettingsRoute,
  AppRestaurantOrdersRoute: AppRestaurantOrdersRoute,
  AppRestaurantPromotionsRoute: AppRestaurantPromotionsRoute,
  AppRestaurantReviewsRoute: AppRestaurantReviewsRoute,
  AppRestaurantsRestaurantIdRoute: AppRestaurantsRestaurantIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminOrdersOrderIdRoute: AppAdminOrdersOrderIdRoute,
  AppAdminRestaurantsRestaurantIdRoute: AppAdminRestaurantsRestaurantIdRoute,
  AppAdminUsersUserIdRoute: AppAdminUsersUserIdRoute,
  AppAdminOrdersIndexRoute: AppAdminOrdersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
